import { Metadata } from "next";

const siteConfig = {
  name: "Maa Unique Dham",
  shortName: "Maa Unique Dham",
  description: "A sacred spiritual platform born in the hills of Darjeeling. Where Maa is not invoked. She Arrives.",
  url: "https://www.maauniquedham.in",
  ogImage: "https://www.maauniquedham.in/logo.png",
  keywords: [
    "Maa Unique Dham",
    "www.maauniquedham.in",
    "Darjeeling",
    "Temple in Darjeeling",
    "Hindu Temple Darjeeling",
    "Best Temple in Darjeeling",
    "Spiritual Places Darjeeling",
    "Maa Durga",
    "Darjeeling Tourism",
    "Spiritual Guidance",
    "Online Puja Booking",
    "Places to visit in Darjeeling",
    "Darjeeling sightseeing",
    "Peaceful places in Darjeeling",
    "Nav Kanya Devi Mandir",
    "Mahant Yogiraj",
    "Shakti Peeth Darjeeling",
    "Spiritual healing Darjeeling",
    "Famous temples in West Bengal",
    "Durga Mandir North Bengal",
    "Religious places in Darjeeling",
    "Dham in Darjeeling",
    "Spiritual travel India",
    "Himalayan spiritual retreat",
    "Maa Durga Mandir Darjeeling",
    "Mahant Yogiraj Darjeeling",
    "Energy healing Darjeeling",
    "Meditation center Darjeeling",
    "Shakti Sadhana Darjeeling",
    "Best spiritual destination Darjeeling",
    "Sacred places in West Bengal",
    "North Bengal temple tour",
    "Darjeeling temple timings",
    "Darjeeling temple list",
    "Durga puja in Darjeeling",
    "Navratri celebration Darjeeling",
    "Himalayan temple photography",
    "Peaceful spots Darjeeling",
    "Religious tourism Darjeeling",
    "Unique Dham contact number",
    "How to reach Maa Unique Dham",
    "Top 10 temples in Darjeeling",
    "Must visit places Darjeeling",
    "Darjeeling spiritual guide",
    "Himalayan masters",
    "Sanatan Dharma Darjeeling",
    "Vedic rituals Himalayas",
    "Online Darshan Darjeeling",
    "Virtual temple tour Darjeeling",
    "Spiritual bloggers Darjeeling",
    "Yoga and meditation Darjeeling",
    "Healing vibrations Himalayas",
    "Maa Durga blessings",
    "Power of Shakti",
    "Ancient Himalayan secrets",
    "Yogic path Darjeeling",
    "Spiritual awakening Darjeeling",
    "Devotional music Darjeeling",
    "Satsang in Darjeeling",
    "Spiritual workshops Darjeeling",
    "Darjeeling pilgrimage",
    "Himalayan goddess temple",
    "Divine intervention Darjeeling",
    "Peace of mind Darjeeling",
    "Stress relief spiritual",
    "Maa Unique Dham address",
    "Best time to visit Darjeeling",
    "Darjeeling travel guide 2024",
    "Sacred Himalayas",
    "Sanatan Shakti",
    "Vedic tradition India",
    "Spiritual enlightenment Darjeeling",
    "Mahakal Temple Darjeeling",
    "Dhir Dham Darjeeling",
    "Japanese Peace Pagoda Darjeeling",
    "Maa Shakti Dham",
    "Dali Monastery Darjeeling",
    "Ghoom Monastery",
    "Tibetan Buddhist Monastery Darjeeling",
    "Best Mandir in Darjeeling",
    "Famous temples in Darjeeling",
    "Darjeeling sightseeing places",
    "Darjeeling tourist spots",
    "Puja in Darjeeling",
    "Nav Kanya Mandir",
    "Ma Durga",
    "Ma Kali",
    "Maa Kali Mandir Darjeeling",
    "Dham in Darjeeling",
    "Uniq Dham",
    "Uniqe Dham",
    "Unique Dham Darjeeling",
    "Maa Uniq",
    "Maa Uniqe",
    "Ma Uniq",
    "Dham Darjeeling",
    "Darjiling Temple",
    "Darjiling Mandir",
    "Hinduism Darjeeling",
    "Spirituality in Himalayas",
    "Himalayan Shakti",
    "Navaratri Darjeeling",
    "Durga Puja Darjeeling 2024",
    "Durga Puja 2024",
    "Kali Puja Darjeeling",
    "Diwali in Darjeeling",
    "Spiritual tour West Bengal",
    "Religious places North Bengal",
    "Best spiritual master Darjeeling",
    "Yoga in Darjeeling",
    "Meditation retreat Himalayas",
    "Energy healing West Bengal",
    "Peaceful place Darjeeling",
    "Top rated temples Darjeeling",
    "Ancient temples Darjeeling",
    "Shiv Mandir Darjeeling",
    "Hanuman Mandir Darjeeling",
    "Ramakrishna Mission Darjeeling",
    "Spiritual guidance online",
    "Book puja online India",
    "Hindu rituals Darjeeling",
    "Vedic chanting Darjeeling",
    "Maa Unique Dham contact info",
    "Maa Unique Dham reviews",
    "Maa Unique Dham images",
    "Maa Unique Dham videos",
    "Spiritual journey India",
    "Divine experiences Darjeeling",
    "Peaceful hills Darjeeling",
    "Darjeeling spiritual tourism",
    "Sanatan Dharma West Bengal",
    "Vedic science Darjeeling",
    "Spiritual lifestyle Darjeeling",
    "Maa Durga status",
    "Shakti power",
    "Himalayan blessings",
    "Maa Unique Dham Mahant",
    "Yogiraj Darjeeling",
    "Spiritual healing North Bengal",
    "Durga Mandir near me",
    "Temple near me Darjeeling",
    "Best place for meditation Darjeeling",
    "Darjeeling holiday spiritual",
    "Temple tour North India",
    "Sacred Darjeeling",
    "Holy places Darjeeling",
    "Mandir Darjeeling list",
    "Darjeeling pilgrimage sites",
    "Maa Unique Dham official website"
  ],
  googleVerification: "mLv150vGWImZ6OzkhcyMd8s89eqNzrAPk-WhTlKfC6M",
};

export function constructMetadata({
  title,
  description = siteConfig.description,
  image = siteConfig.ogImage,
  noIndex = false,
  keywords = [],
  canonicalPath = "/",
}: {
  title?: string;
  description?: string;
  image?: string;
  noIndex?: boolean;
  keywords?: string[];
  canonicalPath?: string;
} = {}): Metadata {
  const fullTitle = title 
    ? (title.includes(siteConfig.name) ? title : `${title} | ${siteConfig.name}`)
    : `${siteConfig.name} | Best Temple in Darjeeling`;

  return {
    title: fullTitle,
    description,
    keywords: [...siteConfig.keywords, ...keywords],
    authors: [{ name: siteConfig.name }],
    creator: siteConfig.name,
    alternates: {
      canonical: canonicalPath,
    },
    // Google uses siteName for the brand name in search results
    openGraph: {
      type: "website",
      locale: "en_US",
      url: siteConfig.url,
      title: fullTitle,
      description,
      siteName: siteConfig.name,
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: fullTitle,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [image],
      creator: "@maauniquedham",
    },
    icons: {
      icon: "/favicon.ico",
      shortcut: "/favicon.ico",
      apple: "/apple-touch-icon.png",
    },
    metadataBase: new URL(siteConfig.url),
    verification: {
      google: siteConfig.googleVerification,
    },
    robots: {
      index: !noIndex,
      follow: !noIndex,
      googleBot: {
        index: true,
        follow: true,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      },
    },
    ...(noIndex && {
      robots: {
        index: false,
        follow: false,
      },
    }),
    category: "religion",
    // For proper brand naming and visual beauty in search/social
    other: {
      "application-name": siteConfig.name,
      "apple-mobile-web-app-title": siteConfig.name,
      "apple-mobile-web-app-capable": "yes",
      "apple-mobile-web-app-status-bar-style": "default",
      "format-detection": "telephone=no",
      "theme-color": "#e95d24", // Sacred Saffron
      "mobile-web-app-capable": "yes",
      "msapplication-TileColor": "#e95d24",
      "msapplication-tap-highlight": "no",
    }
  };
}
